name: Flutter CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar JDK 17, requerido por el Android Gradle plugin
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Paso 3: Configuración del Flutter SDK
      - name: Setup Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5
          cache: true

      # Paso 4: Obtener dependencias, limpiar y construir el APK
      - name: Flutter Pub Get and Build
        run: |
          flutter pub get
          flutter clean
          flutter build apk --release

      # Paso 5: Subir el APK generado como artefacto descargable
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk
